### ISSUE TITLE
How do I convert a PMML model (which was created using RandomForest sklearn) back to sklearn RF model ?

### ISSUE THREAD

**Issue by aishgrt1** [iamDecode/sklearn-pmml-model#1]

**Comment by iamDecode** [comment]
Sorry for the delay! Unfortunately the library is just a work in progress, and only Decision Trees are currently supported. That said, the PMML structure for Random Forests is fairly similar to that of Decision Trees, so supporting them should not be too difficult. I am currently occupied with other work, preventing me from developing this project. However, I do want to add support to Random Forests in the near future.

**Comment by iamDecode** [comment]
Basic Random Forest support was added in [version 0.0.3](https://github.com/iamDecode/sklearn-pmml-model/pull/5). Note that the library is in alpha stage, and may not be robust against all possible PMML models yet.
