### ISSUE TITLE
threshold vs split_value

### ISSUE THREAD

**Issue by kodonnell** [iamDecode/sklearn-pmml-model#12]
[This](https://scikit-learn.org/stable/auto_examples/tree/plot_unveil_tree_structure.html) sklearn example of how to inspect the tree fails to work with one of these trees. It seems to be because `split_value` is used internally instead of `threshold`, but that means [this](https://github.com/scikit-learn/scikit-learn/blob/1495f69242646d239d89a5713982946b8ffcf9d9/sklearn/tree/_tree.pyx#L586-L588) fails.

**Comment by iamDecode** [comment]
Fixed in 3214b291410acbb5e0abf44dbd289670ea674caa
