### ISSUE TITLE
logistic

### ISSUE THREAD

**Issue by yyyooohao** [iamDecode/sklearn-pmml-model#35]
The logistic regression that I use, the linear model that I use, it says in the document that logistic regression is included, why does it show up when I predict  PMML model does not contain RegressionModel.

**Comment by iamDecode** [comment]
Thanks for your interest in `sklearn-pmml-model`! In order for me to help you find the problem, it would be great if you can stick to the issue template. Without an extract of the PMML model you are trying to convert, it is difficult for me to help you.

That being said, based on the error I think the library you used to export the PMML model has converted the original `RegressionModel` to an equivalent `GeneralRegressionModel`. If this is the case, you should be able to generate predictions using `PMMLRidgeClassifier` for classification, or `PMMLRidge` for regression.

**Comment by yyyooohao** [comment]
> Thanks for your interest in `sklearn-pmml-model`! In order for me to help you find the problem, it would be great if you can stick to the issue template. Without an extract of the PMML model you are trying to convert, it is difficult for me to help you.
> 
> That being said, based on the error I think the library you used to export the PMML model has converted the original `RegressionModel` to an equivalent `GeneralRegressionModel`. If this is the case, you should be able to generate predictions using `PMMLRidgeClassifier` for classification, or `PMMLRidge` for regression.

**Comment by yyyooohao** [comment]
> Thanks for your interest in `sklearn-pmml-model`! In order for me to help you find the problem, it would be great if you can stick to the issue template. Without an extract of the PMML model you are trying to convert, it is difficult for me to help you.
> 
> That being said, based on the error I think the library you used to export the PMML model has converted the original `RegressionModel` to an equivalent `GeneralRegressionModel`. If this is the case, you should be able to generate predictions using `PMMLRidgeClassifier` for classification, or `PMMLRidge` for regression.

I used SVM to predict before, and I want to use logistic regression to classify, test the accuracy of the results, and use logistic regression prediction under the linear model. I mainly want to try logistic regression for classification.

**Comment by yyyooohao** [comment]
> Thanks for your interest in `sklearn-pmml-model`! In order for me to help you find the problem, it would be great if you can stick to the issue template. Without an extract of the PMML model you are trying to convert, it is difficult for me to help you.
> 
> That being said, based on the error I think the library you used to export the PMML model has converted the original `RegressionModel` to an equivalent `GeneralRegressionModel`. If this is the case, you should be able to generate predictions using `PMMLRidgeClassifier` for classification, or `PMMLRidge` for regression.

**Comment by yyyooohao** [comment]
> Thanks for your interest in `sklearn-pmml-model`! In order for me to help you find the problem, it would be great if you can stick to the issue template. Without an extract of the PMML model you are trying to convert, it is difficult for me to help you.
> 
> That being said, based on the error I think the library you used to export the PMML model has converted the original `RegressionModel` to an equivalent `GeneralRegressionModel`. If this is the case, you should be able to generate predictions using `PMMLRidgeClassifier` for classification, or `PMMLRidge` for regression.

Well, I can use THE SVM export to PMML to make predictions, but the logical classification prediction will report an error

**Comment by iamDecode** [comment]
I suppose you are using `PMMLLogisticRegression` to make 'logical classification' predictions? In my previous comment, I recommended to use `PMMLRidgeClassifier` instead. To do that, just replace "PMMLLogisticRegression" with "PMMLRidgeClassifier". I think that should work for you.

**Comment by yyyooohao** [comment]
> The parameters you show don't make a lot of sense to me. `max_iter = 2` is way too low to yield any decent classification. I suggest you start with `LogisticRegression()`, so without any arguments. See if that works (it should), and then gradually add arguments to see if it improves performance. Often enough, the default parameters prove to be sufficient.
> 
> If you like to try another model, I suggest trying `RandomForestClassifier`.

The test accuracy of default parameters is not high, which can only reach half of SVM, and it needs to be adjusted, and it does not need too complex network model.

**Comment by yyyooohao** [comment]
> The parameters you show don't make a lot of sense to me. `max_iter = 2` is way too low to yield any decent classification. I suggest you start with `LogisticRegression()`, so without any arguments. See if that works (it should), and then gradually add arguments to see if it improves performance. Often enough, the default parameters prove to be sufficient.
> 
> If you like to try another model, I suggest trying `RandomForestClassifier`.

I tried the random forest,ModuleNotFoundError: No module named 'sklearn_pmml_model.tree._tree'.I use three categories

**Comment by iamDecode** [comment]
Please make sure you installed the library using `pip install sklearn-pmml-model`. This error seems to indicate the Cython code is not compiled, which is only the case if you downloaded this library and are working in that directory directly.

If you, for some reason, cannot use `pip`, running the following command will compile the Cython code inplace, and should fix the issue you have:

```
python setup.py build_ext --inplace
```
I don't recommend this, and it will require a C compile, which is a bit of a pain to setup on windows. More information about this process can be found at https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#from-source.

**Comment by yyyooohao** [comment]
> Please make sure you installed the library using `pip install sklearn-pmml-model`. This error seems to indicate the Cython code is not compiled, which is only the case if you downloaded this library and are working in that directory directly.
> 
> If you, for some reason, cannot use `pip`, running the following command will compile the Cython code inplace, and should fix the issue you have:
> 
> ```
> python setup.py build_ext --inplace
> ```
> 
> I don't recommend this, and it will require a C compiler, which is a bit of a pain to setup on windows. More information about this process can be found at https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#from-source.

I installed the package according to Requerment.txt

**Comment by yyyooohao** [comment]
> Please make sure you installed the library using `pip install sklearn-pmml-model`. This error seems to indicate the Cython code is not compiled, which is only the case if you downloaded this library and are working in that directory directly.
> 
> If you, for some reason, cannot use `pip`, running the following command will compile the Cython code inplace, and should fix the issue you have:
> 
> ```
> python setup.py build_ext --inplace
> ```
> 
> I don't recommend this, and it will require a C compiler, which is a bit of a pain to setup on windows. More information about this process can be found at https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#from-source.

If I use logistic regression to do the tripartite model can't it predict

**Comment by yyyooohao** [comment]
> which is only the case if you downloaded this library and are working in that directory directly.

Can't you just go down and work on it? I don't want to install a C compiler, haha

**Comment by yyyooohao** [comment]
which is only the case if you downloaded this library and are working in that directory directly.
> 
I can use PIP, how can I simply use random forest, I don't want to install c compiler.

**Comment by yyyooohao** [comment]
> Please make sure you installed the library using `pip install sklearn-pmml-model`. This error seems to indicate the Cython code is not compiled, which is only the case if you downloaded this library and are working in that directory directly.
> 
> If you, for some reason, cannot use `pip`, running the following command will compile the Cython code inplace, and should fix the issue you have:
> 
> ```
> python setup.py build_ext --inplace
> ```
> 
> I don't recommend this, and it will require a C compiler, which is a bit of a pain to setup on windows. More information about this process can be found at https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#from-source.
Why do I use logistic regression to do the binary classification of such errors, the first two days can also do three classifications will report errors
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1024)

**Comment by iamDecode** [comment]
If you use `pip` to install the library, no C compiler is necessary. More information on how to install using pip can be found in the documentation: https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#pip. 

`pip` is the standard package manager for Python, and is included with every Python install. The documentation includes a link to more general information about `pip` here: https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing.

**Comment by yyyooohao** [comment]
> If you use `pip` to install the library, no C compiler is necessary. More information on how to install using pip can be found in the documentation: https://sklearn-pmml-model.readthedocs.io/en/latest/install.html#pip.
> 
> `pip` is the standard package manager for Python, and is included with every Python install. The documentation includes a link to more general information about `pip` here: https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing.

I installed packages from Requiest with PIP. Why do I get errors with those models

**Comment by iamDecode** [comment]
> Why do I get errors with those models

You have to let me know which errors you are seeing, otherwise I cannot help you.

---

I am expecting you still installed the packages with `pip` but are still within a clone of this package. If you are working in a copy of this repository, please remove it, start fresh, do a pip install, and try out the example I provided here: https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906271001. If this works, you can proceed to try different models and datasets.

**Comment by yyyooohao** [comment]
> > Why do I get errors with those models
> 
> You have to let me know which errors you are seeing, otherwise I cannot help you.
> 
> I am expecting you still installed the packages with `pip` but are still within a clone of this package. If you are working in a copy of this repository, please remove it, start fresh, do a pip install, and try out the example I provided here: [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906271001). If this works, you can proceed to try different models and datasets.

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1024)
![image](https://user-images.githubusercontent.com/65326115/131986399-f2472743-8f91-40b6-94cf-6a6ba4bfab8c.png)
The error occurred when I used logistic regression or ridge regression, it is ok to carry out binary classification before logistic regression, can triple classification be used? I mainly use it to test binary classification and triple classification. If it is triple classification, do I need to make any modifications。

**Comment by yyyooohao** [comment]
> > Why do I get errors with those models
> 
> You have to let me know which errors you are seeing, otherwise I cannot help you.
> 
> I am expecting you still installed the packages with `pip` but are still within a clone of this package. If you are working in a copy of this repository, please remove it, start fresh, do a pip install, and try out the example I provided here: [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906271001). If this works, you can proceed to try different models and datasets.

Well, use the package version, but don't use it directly in your project.

**Comment by yyyooohao** [comment]
> > Why do I get errors with those models
> 
> You have to let me know which errors you are seeing, otherwise I cannot help you.
> 
> I am expecting you still installed the packages with `pip` but are still within a clone of this package. If you are working in a copy of this repository, please remove it, start fresh, do a pip install, and try out the example I provided here: [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906271001). If this works, you can proceed to try different models and datasets.

![image](https://user-images.githubusercontent.com/65326115/132174309-5c98f3e3-32a7-4a62-bcee-e993aa403ee1.png)
I used logistic to classify them into three categories and found Exception: PMML model does not contain RegressionModel. Reinstalled the package, the dichotomies can be predicted, ridge regression is also such a problem.

**Comment by yyyooohao** [comment]
> > Why do I get errors with those models
> 
> You have to let me know which errors you are seeing, otherwise I cannot help you.
> 
> I am expecting you still installed the packages with `pip` but are still within a clone of this package. If you are working in a copy of this repository, please remove it, start fresh, do a pip install, and try out the example I provided here: [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906271001). If this works, you can proceed to try different models and datasets.

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject,
Do I need to do some configuration when I use GBDT classification.

**Comment by iamDecode** [comment]
> I used logistic to classify them into three categories and found Exception: PMML model does not contain RegressionModel. Reinstalled the package, the dichotomies can be predicted, ridge regression is also such a problem.

Ok I think I understand now. You seem to be using the `multi_class='ovr'` parameter on your `LogisticRegression` class (from https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906867774). This means one-versus-rest regression. This type is not explicitly supported by the library yet, but I am working on adding it right now. 

To get it working in the mean time, you can use the default parameter `multi_class='auto'` or specifically select `multi_class='multinomial'` instead. This type of regression should work!

**Comment by yyyooohao** [comment]
> > I used logistic to classify them into three categories and found Exception: PMML model does not contain RegressionModel. Reinstalled the package, the dichotomies can be predicted, ridge regression is also such a problem.
> 
> Ok I think I understand now. You seem to be using the `multi_class='ovr'` parameter on your `LogisticRegression` class (from [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906867774)). This means one-versus-rest regression. This type is not explicitly supported by the library yet, but I am working on adding it right now.
> 
> To get it working in the mean time, you can use the default parameter `multi_class='auto'` or specifically select `multi_class='multinomial'` instead. This type of regression should work!

![image](https://user-images.githubusercontent.com/65326115/132270498-08173e9d-0873-4383-bba1-18e43d885f70.png)
Well, I had a logistic triage error,Exception: PMML model does not contain RegressionModel.

**Comment by yyyooohao** [comment]
> > I used logistic to classify them into three categories and found Exception: PMML model does not contain RegressionModel. Reinstalled the package, the dichotomies can be predicted, ridge regression is also such a problem.
> 
> Ok I think I understand now. You seem to be using the `multi_class='ovr'` parameter on your `LogisticRegression` class (from [#35 (comment)](https://github.com/iamDecode/sklearn-pmml-model/issues/35#issuecomment-906867774)). This means one-versus-rest regression. This type is not explicitly supported by the library yet, but I am working on adding it right now.
> 
> To get it working in the mean time, you can use the default parameter `multi_class='auto'` or specifically select `multi_class='multinomial'` instead. This type of regression should work!

![image](https://user-images.githubusercontent.com/65326115/132271834-db6dbbd9-69b5-41f7-987a-c9ab41335d6b.png)
soga,Three categories running, ha ha

**Comment by iamDecode** [comment]
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject,

This error typically means you have to re-install numpy (`pip install numpy --upgrade`)

**Comment by iamDecode** [comment]
> soga,Three categories running, ha ha

Glad you got it working! I have just released a new version that should also work with `multi_class='ovr'`. If your initial problem is resolved, can I close this issue?
