### ISSUE TITLE
load pmml to Classifier when y_label is float

### ISSUE THREAD

**Issue by Lovejane-N** [iamDecode/sklearn-pmml-model#44]
Description

Hi, there is an issue of loading pmml to Classifier(both tree and rf), when the y_label is float. The values in tree will always be 0. The problem I found is line254 in tree/tree.py, the returned value will always be None even if one of the value is not None, I am not sure why this happens.

 Steps/Code to Reproduce

the pmml file I tested: see attached file.
[demo.pmml.zip](https://github.com/iamDecode/sklearn-pmml-model/files/9257830/demo.pmml.zip)

python code:
from sklearn_pmml_model.tree import PMMLTreeClassifier
clf = PMMLTreeClassifier(pmml="demo.pmml")
print(clf.tree_.value)

 Expected Results

array([[[2., 2., 1.]],

       [[2., 1., 0.]],

       [[0., 1., 0.]],

       [[2., 0., 0.]],

       [[0., 1., 1.]],

       [[0., 0., 1.]],

       [[0., 1., 0.]]])

 Actual Results

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

#### Versions

macOS-12.0.1-arm64-arm-64bit
Python 3.8.9 (default, Oct 26 2021, 07:25:53) 
[Clang 13.0.0 (clang-1300.0.29.30)]
NumPy 1.22.3
SciPy 1.8.0
Scikit-Learn 1.0.2
sklearn-pmml-model 1.0.0

**Comment by Lovejane-N** [comment]
Hi, I just find that : Element(MutableSequence[Element]), 
the Element is inherited from a MutableSequence, so bool(Element) will be false when the length is 0, which is the situation that the Element is actually a leaf.

**Comment by iamDecode** [comment]
Great, thanks for the detailed report! I managed to reproduce and agree line 254 is the culprit. The `or` was a lazy and incorrect way to check for `None`, and I've addressed it in #45. If all tests/CI passes I hope to release a new version soon to include this fix.
